#!/bin/sh

echo -e "   ._________________.     "
echo -e "   |.---------------.|     \e[34mDistro\e[0m: $(cat /etc/os-release | head -n1 | sed 's/"//g' | sed 's/PRETTY_NAME=//g' | sed 's/NAME=//g')"
echo -e "   ||               ||     \e[34mKernel\e[0m: $(uname -r)"
echo -e "   ||               ||     \e[34mMemory\e[0m: $(free -m | awk '{print $3}' | head -n2 | tail -n1) MiB / $(free -m | awk '{print $2}' | head -n2 | tail -n1) MiB"
echo -e "   ||               ||     \e[34mCache\e[0m: $(free -m | awk '{print $6}' | head -n2 | tail -n1) MiB"
echo -e "   ||               ||     \e[34mThreads\e[0m: $(nproc)"
echo -e "   ||_______________||     \e[34mTasks\e[0m: $(ps aux | wc -l)"
echo -e "   /.-.-.-.-.-.-.-.-.\     \e[34mLocal IP\e[0m: $(ip a | grep 192.168. | cut -d'b' -f1 | cut -d'/' -f1 | sed 's/inet//g' | sed 's/ //g')"
echo -e "  /.-.-.-.-.-.-.-.-.-.\    \e[34mShell\e[0m: $SHELL"
echo -e " /.-.-.-.-.-.-.-.-.-.-.\   \e[34mCpu\e[0m: $(lscpu | grep "Model name" | sed 's/Model name: //g' | xargs)"
echo -e "/______/__________\___o_\  \e[34mUser\e[0m: $(whoami)"
echo -e "\_______________________/  \e[34mModules\e[0m: $(cat /proc/modules | wc -l)"
echo ""

